#!/usr/bin/env python3
"""Estate-shaped corpus v1 for S1 and S3 (WP0(e): OI-1003-Q19, OI-1003-Q23, R-N13).

R23 corpus v1 (r23_corpus.py) is 23 large regular files, so it never
exercises the per-entry costs of a real agent estate. This script builds a
git-heavy, many-small-file tree that models what bulkload carries from a live
estate. It is deterministic from (--seed, --scale) and sealed by a content
identity. Exact counts per scale are in
docs/evidence/estate-corpus-v1-2026-10-03.md.

Shape. The corpus root models an agent's $HOME:
  git/rNN-*/                 non-bare repositories with history: a --no-ff
                             merge, an annotated and a lightweight tag, an
                             unmerged `side` branch, and a packing profile
                             per repository: loose, packed, or mixed (a pack
                             plus loose objects and refs written after it).
  git/rNN-*.worktrees/<w>    a linked worktree on its own branch, with a
                             commit, an unstaged edit and an untracked file.
  git/rNN-*.worktrees/detached   a detached-HEAD linked worktree. It holds
                             only an untracked file, so `mutate` can move
                             its HEAD.
  git/rNN-*/.claude/worktrees/agent-*   an ignored in-repository worktree.
  git/mirrors/*.git          bare repositories, filled by a push.
  In the main checkouts: real stashes (one with untracked files), a dirty
  index (a staged edit with an unstaged edit on top, a staged new file and an
  intent-to-add entry), unstaged edits, untracked files, ignored build
  outputs, a nested repository inside the work tree, a tracked symlink, an
  executable, and in two repositories a large binary blob.
  projects/*/node_modules    node_modules-like fan-out: scoped packages,
                             nested node_modules, identical LICENSE files and
                             relative .bin symlinks.
  .cache/agent-cache/        a hex fan-out of tiny files.
  data/                      a few large files (random, text, sparse pattern).
  .codex/ .claude/           JSONL transcripts (Codex-like and Claude-like),
                             history, settings and todos. There are .jsonl.zst
                             archives when the `zstd` CLI is on PATH; the
                             devShell has it through stdenv. Without zstd they
                             are skipped and SEAL.json records the note.
  SQLite                     stores in journal_mode=DELETE, plus one WAL
                             crash image (see below).
  Dotfiles, a 0700 .ssh, 0600, 0640 and 0444 files, symlinks (relative to a
  file and to a directory, dangling, absolute, a two-link loop, a link to a
  link), empty directories, unusual-but-legal names and a 32-deep chain.

Determinism. Every generated byte comes from SHAKE-256 (FIPS 202), keyed by
seed, scale and a label. As in r23_corpus.py, nothing uses `random`, so the
output does not depend on the Python version.
Git runs with these settings:
  - an isolated HOME and global config (GIT_CONFIG_GLOBAL);
  - GIT_CONFIG_NOSYSTEM=1, GIT_ATTR_NOSYSTEM=1, TZ=UTC and LC_ALL=C;
  - inherited GIT_* variables dropped, and GIT_CEILING_DIRECTORIES set to the
    corpus root;
  - a fixed author and committer identity;
  - a logical clock: every git call gets the next GIT_AUTHOR_DATE and
    GIT_COMMITTER_DATE, so commits, tags, stashes and every reflog line are
    fixed.
Objects are byte-stable because the global config pins:
  - pack.threads=1, core.looseCompression=1, pack.compression=6, and the pack
    window and depth;
  - pack.writeReverseIndex=true, and no bitmaps;
  - gc.auto=0, maintenance.auto=false, and index.threads=1;
  - no untracked cache, split index or fsmonitor;
  - reflog and prune expiry `never`, so nothing depends on the wall clock.
Repositories are created with an explicit template, so version-dependent
sample hooks do not enter the corpus. They use --object-format=sha1 and
--ref-format=files (git >= 2.45). Their .git/config is rewritten to the text
Linux `git init` writes, so macOS's ignorecase and precomposeunicode lines do
not enter the identity. The corpus repositories have only `.sample` hooks.
Nothing sets core.hooksPath, and nothing passes --no-verify. umask is 022.
Mtimes are left as git and the filesystem set them (so no index is racily
clean); they are not part of the identity.

Identity. MANIFEST.tsv has one line per entry below corpus/, sorted by path
bytes. The columns are path, type (d, f or l), mode, size, SHAKE-256/256
content digest, symlink target and normalisation:
  - mode is the permission bits, or `-` for a symlink, whose mode differs by
    OS;
  - a path or target uses backslash escapes for backslash, control
    characters and undecodable bytes.
The manifest excludes directory sizes, mtimes, ctimes, inodes, devices, link
counts and owners. The identity is the SHAKE-256/256 of MANIFEST.tsv.
SHAKE-256 is r23_corpus.py's generator primitive and is in hashlib; r23's
BLAKE3 needs b3sum, which the devShell does not carry. RECORDED holds the
identities measured with the devShell toolchain. When the toolchain matches,
`generate` compares against them and fails on a mismatch (recorded=False).
Three kinds of file hold bytes that are not a function of the seed, and are
normalised explicitly:
  git-index  every `index` file of a git directory (a main checkout's and
             each linked worktree's). Each entry's stat words (ctime, mtime,
             dev, ino, uid, gid and size) are zeroed, and the trailing
             checksum, which covers them, is dropped. Mode, object id, flags,
             path and the extensions (TREE) stay. An index with a
             stat-bearing extension (UNTR, FSMN or link) is a problem. The
             size column is the real size, because entries are fixed width.
  root       a linked worktree's `.git` file and its administration's `gitdir`
             hold absolute paths. Bulkload's carry resolves them absolutely,
             so relative worktrees are not used. The corpus root recorded in
             SEAL.json is replaced by @CORPUS_ROOT@ before hashing, and the
             size column is the normalised size. Any other file under a git
             directory that contains the root is a problem.
  raw        everything else, including loose objects, packs, .idx, .rev,
             commit-graph, packed-refs, reflogs and the SQLite files.
SQLite DELETE-mode files are stable for one SQLite version; the header
records the writer's version.
The WAL crash image is a main database plus its -wal, copied while the
writing connection was still open:
  - SQLite seeds each new WAL with random salts, so the generator rewrites
    both salts to seed-derived values and recomputes every frame checksum;
  - it then proves that a copy opens with integrity_check ok and the expected
    row count;
  - no -shm is written; it is a lock and index cache that the first opener
    rebuilds.
Caveat: any WAL-aware opener, read-only included (as provider_sqlite's
backup opens it), creates <db>-shm beside the image. A verify after such a
read reports that path as an extra entry.

Not modelled:
  - hardlinks, holes (sparse files), xattrs and ACLs;
  - FIFOs, sockets and devices (bulkload refuses non-regular seats);
  - names with control or format characters (PATH_NOT_PORTABLE).
Case-colliding and NFD names are avoided, so the tree is legal on APFS.

Cross-host. The identity is stable for one toolchain: git (pack layout), its
zlib, SQLite (the header) and zstd (frames). SEAL.json records their
versions, and the devShell pins all of them. A corpus is not relocatable:
linked worktrees point at the absolute path it was generated in. `verify`
still accepts a moved copy (it normalises with the recorded root) and reports
relocated=1, but git must never be run in such a copy.

Mutation (the S3 knob, `--mutate N`, spelled `mutate DEST N`). Round r is the
number of mutations so far, plus one. N operations cycle through, in a
seed-shuffled order with seed-chosen targets:
  edit       overwrite 64 bytes in place;
  append     append a JSONL line;
  new        create a file;
  delete     remove a file;
  commit     a new commit on a repository's unmerged `side` branch, through
             plumbing (side is checked out nowhere);
  head-move  `checkout --detach` in a detached worktree.
It writes DEST/mutations/round-RRRR.json with:
  - the operations, and the identity before and after;
  - the exact manifest difference: added, removed and modified;
  - stat_only: the same manifest row with a new inode, size, mtime or ctime,
    such as a rewritten index or a directory whose listing changed;
  - reads_allowed: the regular files among added, modified and stat_only. An
    S3 rerun may read those files and nothing else.
SEAL.json and MANIFEST.tsv then move to the new identity.

Usage:
  estate_corpus.py generate DEST [--seed S] [--scale small|estate]
      DEST must be new. Writes DEST/corpus, DEST/MANIFEST.tsv, DEST/SEAL.json
      and DEST/README.md.
  estate_corpus.py verify DEST       exit 0 only if DEST/corpus matches its seal
  estate_corpus.py manifest CORPUS [--root R]
  estate_corpus.py mutate DEST N     apply N deterministic changes (S3)
  estate_corpus.py selftest          optional-tier round trip at scale small
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import os
import platform
import re
import shutil
import sqlite3
import stat
import struct
import subprocess
import sys
import tempfile
import time
from collections.abc import Iterable, Iterator
from pathlib import Path

sys.dont_write_bytecode = True  # no __pycache__ beside the scripts
sys.path.insert(0, str(Path(__file__).resolve().parent))
from r23_corpus import RUN, TEXT_TABLE  # noqa: E402

FORMAT = "bulkload-estate-corpus-v1"
DEFAULT_SEED = "bulkload-estate-corpus-v1"
HISTORY_EPOCH = 1_767_225_600  # 2026-01-01T00:00:00Z, the first git timestamp
MUTATION_EPOCH = 1_790_985_600  # 2026-10-03T00:00:00Z; round r starts r days on
ROOT_TOKEN = b"@CORPUS_ROOT@"
KIB = 1 << 10
MIB = 1 << 20
BLOCK = MIB
LEAK_SCAN_LIMIT = 64 * MIB
MIN_GIT = (2, 45)
HERE = Path(__file__).resolve()
MANIFEST_HEADER = (
    "# bulkload-estate-corpus manifest v1\t"
    "path\ttype\tmode\tsize\tshake256\ttarget\tnorm\n"
)
KINDS = ("edit", "append", "new", "delete", "commit", "head-move")
# Identities measured with the devShell toolchain on sting (x86_64-linux), see
# docs/evidence/estate-corpus-v1-2026-10-03.md. The self-test compares against
# them only when the toolchain matches; a generator change that moves an
# identity must update this table and the evidence.
DEVSHELL_TOOLS = {
    "git": "2.54.0",
    "git_zlib": "zlib-ng: 2.3.3",
    "sqlite": "3.53.1",
    "zstd": "1.5.7",
}
RECORDED: dict[tuple[str, str], tuple[str, dict[str, str]]] = {
    ("small", "bulkload-estate-corpus-v1"): (
        "b36454548957e9bac0b4aefce6e54cf90335df0323d152ececad139aa09a29be",
        DEVSHELL_TOOLS,
    ),
    ("estate", "bulkload-estate-corpus-v1"): (
        "0bd1104ecb67e160689dba4719f34dacf768420016180b38329f3064170c4baf",
        DEVSHELL_TOOLS,
    ),
}


class CorpusError(Exception):
    """A generation, verification or mutation step failed."""


@dataclasses.dataclass(frozen=True)
class Scale:
    repos: int
    files: tuple[int, int]
    commits: tuple[int, int]
    repo_blob: int
    large: tuple[tuple[str, str, int], ...]
    node_projects: int
    node_packages: int
    cache_files: int
    codex_sessions: int
    claude_sessions: int
    transcript_lines: tuple[int, int]
    zst_sessions: int
    sqlite_dbs: int
    sqlite_rows: tuple[int, int]


SCALES = {
    "small": Scale(
        repos=3,
        files=(24, 40),
        commits=(5, 7),
        repo_blob=MIB,
        large=(
            ("data/vm/disk.img", "sparse", 3 * MIB),
            ("data/datasets/blob.bin", "random", 2 * MIB + 17),
            ("data/logs/archive.log", "text", MIB + 3),
        ),
        node_projects=1,
        node_packages=24,
        cache_files=64,
        codex_sessions=3,
        claude_sessions=3,
        transcript_lines=(12, 60),
        zst_sessions=1,
        sqlite_dbs=3,
        sqlite_rows=(300, 900),
    ),
    "estate": Scale(
        repos=24,
        files=(300, 2400),
        commits=(12, 40),
        repo_blob=64 * MIB,
        large=(
            ("data/vm/disk.img", "sparse", 1024 * MIB),
            ("data/datasets/blob-a.bin", "random", 512 * MIB + 4_099),
            ("data/logs/archive.log", "text", 256 * MIB + 77),
            ("data/datasets/blob-b.bin", "random", 128 * MIB),
            ("data/backup/home.tar", "text", 96 * MIB + 5),
        ),
        node_projects=3,
        node_packages=900,
        cache_files=15_000,
        codex_sessions=300,
        claude_sessions=500,
        transcript_lines=(40, 1_500),
        zst_sessions=24,
        sqlite_dbs=10,
        sqlite_rows=(2_000, 60_000),
    ),
}

WORDS = (
    "acc", "apply", "batch", "buffer", "bytes", "carry", "chunk", "close",
    "commit", "count", "cursor", "delta", "digest", "drain", "emit", "entry",
    "error", "fence", "flush", "frame", "hash", "head", "index", "inode",
    "item", "key", "ledger", "limit", "load", "map", "merge", "mode",
    "node", "offset", "open", "pack", "parse", "path", "peer", "plan",
    "pool", "probe", "queue", "read", "record", "ref", "repo", "resume",
    "row", "scan", "seal", "seat", "send", "size", "slot", "stage",
    "state", "store", "sync", "tree", "value", "walk", "write", "yield",
)  # fmt: skip
ENDS = (";", " {", "}", ",", ")", "")
LANGS = (("rs", "Cargo.toml"), ("py", "pyproject.toml"), ("ts", "package.json"),
         ("go", "go.mod"))  # fmt: skip
# Unusual but legal on Linux and APFS: no control or format characters, no
# case-colliding pairs, NFC only, at most 255 bytes.
NAMES = (
    "with space.txt", "-leading-dash", "trailing space ", "caf\u00e9-nfc.txt",
    "\u65e5\u672c\u8a9e\u306e\u30d5\u30a1\u30a4\u30eb.md", "emoji-\U0001f980.rs",
    "quote'single.txt", 'quote"double.txt', "back\\slash.txt", "colon:name.txt",
    "star*glob?.txt", "brackets[1](2){3}.txt", "percent%20encoded.txt",
    "hash#and&amp;.txt", "x" * 255, "\u00e9" * 125 + ".txt",
    "dir with spaces/inner file.txt", ".hidden-dir/.hidden-file",
)  # fmt: skip
LINKS = (
    ("links/rel-file", "../names/with space.txt"),
    ("links/rel-dir", "../dotfiles"),
    ("links/dangling", "../nowhere/missing.txt"),
    ("links/abs-outside", "/dev/null"),
    ("links/loop-a", "loop-b"),
    ("links/loop-b", "loop-a"),
    ("links/chain", "rel-file"),
)
EMPTY_DIRS = ("Downloads", ".local/state/agent", ".cache/empty",
              "projects/scratch/tmp", "names/empty dir")  # fmt: skip
GITIGNORE = b"""/target/
/build/
/dist/
node_modules/
__pycache__/
*.log
.env.local
.claude/worktrees/
"""
REPO_CONFIG = b"""[core]
\trepositoryformatversion = 0
\tfilemode = true
\tbare = false
\tlogallrefupdates = true
"""
BARE_CONFIG = b"""[core]
\trepositoryformatversion = 0
\tfilemode = true
\tbare = true
"""
GLOBAL_CONFIG = """[user]
\tname = Estate Corpus
\temail = estate-corpus@example.invalid
[init]
\tdefaultBranch = main
[core]
\tautocrlf = false
\tsafecrlf = false
\tfsmonitor = false
\tuntrackedCache = false
\tsplitIndex = false
\tlooseCompression = 1
\tsymlinks = true
\tfileMode = true
\tquotePath = false
[pack]
\tthreads = 1
\tcompression = 6
\twindow = 10
\tdepth = 50
\twriteReverseIndex = true
\tuseBitmaps = false
[repack]
\twriteBitmaps = false
\tuseDeltaIslands = false
[gc]
\tauto = 0
\tautoPackLimit = 0
\tautoDetach = false
\twriteCommitGraph = false
\treflogExpire = never
\treflogExpireUnreachable = never
\tpruneExpire = never
\tworktreePruneExpire = never
[maintenance]
\tauto = false
[index]
\tversion = 2
\tthreads = 1
\trecordEndOfIndexEntries = false
\trecordOffsetTable = false
\tskipHash = false
[feature]
\tmanyFiles = false
\texperimental = false
[fetch]
\twriteCommitGraph = false
[transfer]
\tunpackLimit = 1
[receive]
\tautogc = false
\tunpackLimit = 1
[commit]
\tgpgSign = false
[tag]
\tgpgSign = false
[push]
\tgpgSign = false
[worktree]
\tuseRelativePaths = false
[commitGraph]
\tgenerationVersion = 2
[advice]
\tdetachedHead = false
[color]
\tui = false
"""
TEMPLATE_DESCRIPTION = (
    b"Unnamed repository; edit this file 'description' to name the repository.\n"
)
TEMPLATE_EXCLUDE = b"# git ls-files --others --exclude-from=.git/info/exclude\n*.swp\n"
SAMPLE_HOOK = (
    b"#!/bin/sh\n# Inactive sample: drop the .sample suffix to enable.\nexit 0\n"
)
LICENSE = (
    b"MIT License\n\n"
    + (
        b"Permission is hereby granted, free of charge, to any person obtaining a "
        b"copy of this software, to deal in the Software without restriction.\n"
    )
    * 8
)


# ---- deterministic bytes ---------------------------------------------------


def shake(label: str, size: int) -> bytes:
    return hashlib.shake_256(label.encode()).digest(size)


class Det:
    """A SHAKE-256 stream keyed by a label; the same on every Python."""

    def __init__(self, label: str) -> None:
        self.label = label
        self._buf = b""
        self._pos = 0
        self._block = 0

    def take(self, size: int) -> bytes:
        while len(self._buf) - self._pos < size:
            fresh = shake(f"{self.label}#{self._block}", 4096)
            self._buf = self._buf[self._pos :] + fresh
            self._pos = 0
            self._block += 1
        out = self._buf[self._pos : self._pos + size]
        self._pos += size
        return out

    def below(self, bound: int) -> int:
        if bound <= 0:
            raise ValueError("bound must be positive")
        limit = (1 << 64) - (1 << 64) % bound
        while True:
            value = int.from_bytes(self.take(8), "big")
            if value < limit:
                return value % bound

    def between(self, low: int, high: int) -> int:
        return low + self.below(high - low + 1)

    def choice(self, items: list[str] | tuple[str, ...]) -> str:
        return items[self.below(len(items))]

    def chance(self, one_in: int) -> bool:
        return self.below(one_in) == 0

    def shuffled(self, items: Iterable[str]) -> list[str]:
        out = list(items)
        for i in range(len(out) - 1, 0, -1):
            j = self.below(i + 1)
            out[i], out[j] = out[j], out[i]
        return out

    def word(self) -> str:
        return WORDS[self.below(len(WORDS))]

    def hex(self, size: int) -> str:
        return self.take(size).hex()

    def uuid(self) -> str:
        h = self.hex(16)
        return f"{h[:8]}-{h[8:12]}-4{h[13:16]}-a{h[17:20]}-{h[20:32]}"


def stream(label: str, size: int) -> Iterator[bytes]:
    """r23_corpus.py's counter mode: block i is SHAKE-256(label/i)."""
    index = 0
    while size > 0:
        block = shake(f"{label}/{index}", min(size, BLOCK))
        yield block
        size -= len(block)
        index += 1


def blob(label: str, kind: str, size: int) -> Iterator[bytes]:
    offset = 0
    for block in stream(label, size):
        if kind == "text":
            block = block.translate(TEXT_TABLE)
        elif kind == "sparse":
            out = bytearray(block)
            for start in range(0, len(out), RUN):
                if ((offset + start) // RUN) % 2 == 0:
                    end = min(start + RUN, len(out))
                    out[start:end] = bytes(end - start)
            block = bytes(out)
        offset += len(block)
        yield block


def prose(label: str, size: int) -> str:
    return shake(label, size).translate(TEXT_TABLE).decode("ascii")


def source_text(label: str, lines: int) -> bytes:
    raw = shake(label, lines * 10)
    out = []
    for i in range(lines):
        row = raw[i * 10 : i * 10 + 10]
        words = " ".join(WORDS[b % len(WORDS)] for b in row[2 : 3 + row[1] % 8])
        out.append("    " * (row[0] % 4) + words + ENDS[(row[0] >> 2) % 6] + "\n")
    return "".join(out).encode()


def iso(epoch: int) -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S.000Z", time.gmtime(epoch))


def jsonl(rows: Iterable[object]) -> bytes:
    return b"".join(
        json.dumps(row, separators=(",", ":")).encode() + b"\n" for row in rows
    )


# ---- filesystem --------------------------------------------------------------


def put(path: Path, data: bytes | Iterable[bytes], mode: int = 0o644) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    with path.open("wb") as handle:
        for block in [data] if isinstance(data, bytes) else data:
            handle.write(block)
            written += len(block)
    path.chmod(mode)
    return written


def link(path: Path, target: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    os.symlink(target, path)


# ---- git ---------------------------------------------------------------------


class Git:
    """Git with an isolated HOME and config and a logical clock."""

    def __init__(self, scratch: Path, root: Path, clock: int) -> None:
        home = scratch / "home"
        self.template = scratch / "template"
        home.mkdir()
        put(self.template / "description", TEMPLATE_DESCRIPTION)
        put(self.template / "info" / "exclude", TEMPLATE_EXCLUDE)
        for hook in ("pre-commit.sample", "commit-msg.sample"):
            put(self.template / "hooks" / hook, SAMPLE_HOOK, 0o755)
        config = scratch / "gitconfig"
        config.write_text(GLOBAL_CONFIG)
        env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
        env.update(
            HOME=str(home),
            XDG_CONFIG_HOME=str(home / ".config"),
            GIT_CONFIG_GLOBAL=str(config),
            GIT_CONFIG_NOSYSTEM="1",
            GIT_ATTR_NOSYSTEM="1",
            GIT_CEILING_DIRECTORIES=str(root),
            GIT_TERMINAL_PROMPT="0",
            GIT_EDITOR="true",
            GIT_PAGER="cat",
            GIT_AUTHOR_NAME="Estate Corpus",
            GIT_AUTHOR_EMAIL="estate-corpus@example.invalid",
            GIT_COMMITTER_NAME="Estate Corpus",
            GIT_COMMITTER_EMAIL="estate-corpus@example.invalid",
            TZ="UTC",
            LC_ALL="C",
            LANG="C",
        )
        self.env = env
        self.clock = clock

    def raw(
        self,
        cwd: Path,
        *args: str,
        stdin: bytes | None = None,
        extra: dict[str, str] | None = None,
    ) -> bytes:
        self.clock += 61
        stamp = f"@{self.clock} +0000"
        env = {**self.env, "GIT_AUTHOR_DATE": stamp, "GIT_COMMITTER_DATE": stamp}
        env.update(extra or {})
        done = subprocess.run(
            ["git", *args], cwd=cwd, env=env, input=stdin, capture_output=True
        )
        if done.returncode != 0:
            err = done.stderr.decode(errors="replace").strip()
            raise CorpusError(f"git {' '.join(args)} in {cwd}: {err}")
        return done.stdout

    def run(self, cwd: Path, *args: str, **kwargs: object) -> str:
        return self.raw(cwd, *args, **kwargs).decode()  # type: ignore[arg-type]

    def init(self, path: Path, bare: bool = False) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        args = ["init", "-q", f"--template={self.template}", "--object-format=sha1"]
        args += ["--ref-format=files", "-b", "main"]
        self.run(path.parent, *args, *(["--bare"] if bare else []), path.name)
        gitdir = path if bare else path / ".git"
        (gitdir / "config").write_bytes(BARE_CONFIG if bare else REPO_CONFIG)


def edit_lines(path: Path, det: Det, label: str) -> None:
    lines = path.read_bytes().splitlines(keepends=True)
    at = det.below(len(lines) + 1)
    drop = min(det.below(4), len(lines) - at)
    fresh = source_text(label, 1 + det.below(6)).splitlines(keepends=True)
    lines[at : at + drop] = fresh
    path.write_bytes(b"".join(lines))


def repo_name(i: int) -> str:
    return f"r{i:02d}-{WORDS[(i * 37 + 11) % len(WORDS)]}"


def features(i: int) -> dict[str, object]:
    """Per-repository estate state. Repository 0 carries every feature."""
    return {
        "pack": ("mixed", "loose", "packed")[i % 3],
        "branch_worktree": i % 3 != 2,
        "detached_worktree": i % 4 == 0,
        "agent_worktree": i % 6 == 0,
        "stash": i % 2 == 0,
        "dirty": i % 3 == 0,
        "nested": i % 8 == 0,
        "bare": i % 6 == 2,
        "commit_graph": i % 4 == 0,
        "big_blob": i % 12 == 0,
    }


def commit_message(det: Det, n: int) -> str:
    return f"{det.word()}: {det.word()} the {det.word()} {det.word()} ({n})"


def build_repo(g: Git, corpus: Path, base: str, scale: Scale, i: int) -> dict:
    det = Det(f"{base}/repo/{i}")
    name = repo_name(i)
    rel = f"git/{name}"
    path = corpus / rel
    feat = features(i)
    lang, manifest_name = LANGS[i % len(LANGS)]
    label = f"{base}/{rel}"
    g.init(path)
    put(path / "README.md", f"# {name}\n\n".encode() + source_text(f"{label}/r", 12))
    put(path / ".gitignore", GITIGNORE)
    put(path / manifest_name, f"# {name} {lang} manifest\n".encode())
    put(
        path / "scripts/build.sh",
        b"#!/bin/sh\nset -eu\n" + source_text(label, 8),
        0o755,
    )
    for doc in ("v1", "v2"):
        put(path / f"docs/guide/{doc}.md", source_text(f"{label}/{doc}", 30))
    link(path / "docs/latest.md", "guide/v2.md")
    put(path / "assets/logo.bin", shake(f"{label}/logo", 2048 + det.below(14_336)))
    if feat["big_blob"]:
        put(path / "assets/model.bin", stream(f"{label}/model", scale.repo_blob))
    nfiles = det.between(*scale.files)
    modules = max(1, nfiles // 25)
    tracked = ["README.md", "docs/guide/v1.md", "docs/guide/v2.md"]
    for k in range(nfiles):
        module = f"src/{WORDS[(k % modules * 5 + i) % len(WORDS)]}_{k % modules:02d}"
        rel_file = f"{module}/{det.word()}_{k:04d}.{lang}"
        put(path / rel_file, source_text(f"{label}/{rel_file}", 10 + det.below(150)))
        tracked.append(rel_file)
    g.run(path, "add", "-A")
    g.run(path, "commit", "-q", "-m", "Initial import")
    commits = det.between(*scale.commits)
    for c in range(1, commits):
        if c == 2:
            g.run(path, "tag", "-a", "v0.1.0", "-m", "Release v0.1.0")
        if c == commits // 2:
            g.run(path, "switch", "-q", "-c", "side")
            for s in range(2):
                edit_lines(path / det.choice(tracked), det, f"{label}/side/{s}")
                g.run(path, "commit", "-q", "-am", f"side: {commit_message(det, s)}")
            feature = f"feat/{det.word()}"
            g.run(path, "switch", "-q", "-c", feature, "main")
            added = f"src/feature_{i:02d}/{det.word()}.{lang}"
            put(path / added, source_text(f"{label}/feature", 40))
            edit_lines(path / det.choice(tracked), det, f"{label}/feature/edit")
            g.run(path, "add", "-A")
            g.run(path, "commit", "-q", "-m", f"feature: {commit_message(det, c)}")
            g.run(path, "switch", "-q", "main")
            g.run(path, "merge", "-q", "--no-ff", "-m", f"Merge {feature}", feature)
            tracked.append(added)
            if feat["pack"] == "mixed":
                g.run(path, "repack", "-a", "-d", "-q")
                g.run(path, "pack-refs", "--all")
        for e in range(1 + det.below(max(1, nfiles // 40))):
            edit_lines(path / det.choice(tracked), det, f"{label}/c{c}/e{e}")
        if det.chance(4):
            added = f"src/added_{c:02d}/{det.word()}.{lang}"
            put(path / added, source_text(f"{label}/c{c}/new", 20 + det.below(60)))
            tracked.append(added)
        if det.chance(8) and len(tracked) > 12:
            gone = tracked.pop(3 + det.below(len(tracked) - 3))
            (path / gone).unlink()
        g.run(path, "add", "-A")
        g.run(path, "commit", "-q", "-m", commit_message(det, c))
    g.run(path, "tag", "v0.2.0")
    if feat["pack"] == "packed":
        g.run(path, "repack", "-a", "-d", "-q")
        g.run(path, "pack-refs", "--all")
    repo: dict[str, object] = {
        "name": name,
        "path": rel,
        "lang": lang,
        "features": feat,
        "files": nfiles,
        "worktrees": [],
        "stashes": 0,
    }
    if feat["bare"]:
        mirror = f"git/mirrors/{name}.git"
        g.init(corpus / mirror, bare=True)
        g.run(path, "remote", "add", "origin", f"../mirrors/{name}.git")
        g.run(path, "push", "-q", "origin", "main", "side", "--tags")
        repo["bare"] = mirror
    if feat["stash"]:
        edit_lines(path / det.choice(tracked), det, f"{label}/stash/0")
        g.run(path, "stash", "push", "-q", "-m", f"wip: {det.word()} {det.word()}")
        edit_lines(path / det.choice(tracked), det, f"{label}/stash/1")
        put(path / "scratch/untracked-idea.md", prose(f"{label}/stash/u", 700).encode())
        g.run(path, "stash", "push", "-q", "-u", "-m", f"wip: try {det.word()}")
        repo["stashes"] = 2
    worktrees: list[dict[str, str]] = []
    if feat["branch_worktree"]:
        wname = det.word()
        wrel = f"git/{name}.worktrees/{wname}"
        g.run(
            path,
            "worktree",
            "add",
            "-q",
            "-b",
            f"wt/{wname}",
            f"../{name}.worktrees/{wname}",
            "main",
        )
        wpath = corpus / wrel
        edit_lines(wpath / det.choice(tracked), det, f"{label}/wt/commit")
        g.run(wpath, "commit", "-q", "-am", f"wt: {commit_message(det, 0)}")
        edit_lines(wpath / det.choice(tracked), det, f"{label}/wt/unstaged")
        put(wpath / "NOTES.md", prose(f"{label}/wt/notes", 900).encode())
        worktrees.append({"kind": "branch", "path": wrel, "branch": f"wt/{wname}"})
    if feat["detached_worktree"]:
        wrel = f"git/{name}.worktrees/detached"
        g.run(
            path,
            "worktree",
            "add",
            "-q",
            "--detach",
            f"../{name}.worktrees/detached",
            "HEAD~1",
        )
        put(corpus / wrel / "scratch-notes.txt", prose(f"{label}/det", 400).encode())
        worktrees.append({"kind": "detached", "path": wrel})
    if feat["agent_worktree"]:
        aid = det.hex(4)
        wrel = f"{rel}/.claude/worktrees/agent-{aid}"
        g.run(
            path,
            "worktree",
            "add",
            "-q",
            "-b",
            f"agent/{aid}",
            f".claude/worktrees/agent-{aid}",
            "HEAD",
        )
        edit_lines(corpus / wrel / det.choice(tracked), det, f"{label}/agent")
        worktrees.append({"kind": "agent", "path": wrel, "branch": f"agent/{aid}"})
    for wt in worktrees:
        gitfile = (corpus / wt["path"] / ".git").read_text().strip()
        wt["admin"] = f"{rel}/.git/worktrees/{gitfile.rsplit('/', 1)[-1]}"
    repo["worktrees"] = worktrees
    if feat["dirty"]:
        picks = det.shuffled(tracked)
        edit_lines(path / picks[0], det, f"{label}/dirty/staged")
        g.run(path, "add", "--", picks[0])
        edit_lines(path / picks[0], det, f"{label}/dirty/on-top")
        edit_lines(path / picks[1], det, f"{label}/dirty/unstaged")
        staged_new = f"src/staged_{det.word()}.{lang}"
        put(path / staged_new, source_text(f"{label}/dirty/new", 25))
        g.run(path, "add", "--", staged_new)
        intent = f"docs/draft-{det.word()}.md"
        put(path / intent, source_text(f"{label}/dirty/intent", 9))
        g.run(path, "add", "-N", "--", intent)
        put(path / "notes/todo.md", prose(f"{label}/dirty/todo", 500).encode())
        put(path / "notes/ideas/next.md", prose(f"{label}/dirty/next", 300).encode())
    if feat["nested"]:
        nrel = f"{rel}/vendor/{det.word()}-lib"
        nested = corpus / nrel
        g.init(nested)
        for k in range(5):
            put(nested / f"lib/part_{k}.c", source_text(f"{label}/nested/{k}", 30))
        g.run(nested, "add", "-A")
        g.run(nested, "commit", "-q", "-m", "Vendor import")
        edit_lines(nested / "lib/part_0.c", det, f"{label}/nested/edit")
        g.run(nested, "commit", "-q", "-am", "Vendor fix")
        repo["nested"] = nrel
    for k in range(3 + det.below(10)):
        ext = det.choice(("d", "rlib", "rmeta", "o"))
        out = f"target/debug/deps/{det.word()}-{det.hex(8)}.{ext}"
        put(path / out, shake(f"{label}/target/{k}", 512 + det.below(32 * KIB)))
    put(path / "debug.log", prose(f"{label}/log", 2_000 + det.below(20_000)).encode())
    put(path / ".env.local", f"CORPUS_PROFILE=dev\nCORPUS_SEAT={det.hex(8)}\n".encode())
    if feat["commit_graph"]:
        g.run(path, "commit-graph", "write", "--reachable", "--no-progress")
    repo["commits"] = int(g.run(path, "rev-list", "--count", "--branches", "--tags"))
    return repo


# ---- non-git estate state ------------------------------------------------------


def build_home(corpus: Path, base: str) -> None:
    det = Det(f"{base}/home")
    for name in (".bashrc", ".profile", ".zshrc", ".inputrc", ".tmux.conf"):
        put(corpus / name, source_text(f"{base}/home/{name}", 20 + det.below(60)))
    put(
        corpus / ".gitconfig",
        b"[user]\n\tname = Agent\n\temail = agent@example.invalid\n",
    )
    put(corpus / ".config/git/ignore", b".DS_Store\n*.swp\n")
    put(
        corpus / ".config/nix/nix.conf", b"experimental-features = nix-command flakes\n"
    )
    put(corpus / ".config/home-manager/home.nix", source_text(f"{base}/hm", 40))
    put(corpus / ".ssh/config", b"Host lab\n  HostName lab.example.invalid\n", 0o600)
    put(corpus / ".ssh/known_hosts", prose(f"{base}/known", 600).encode())
    (corpus / ".ssh").chmod(0o700)
    session = {"account": "corpus", "session": det.hex(16)}
    put(corpus / ".config/agent/auth.json", json.dumps(session).encode(), 0o600)
    put(corpus / "dotfiles/nvim/init.lua", source_text(f"{base}/nvim", 40))
    put(corpus / "dotfiles/nvim/lua/plugins.lua", source_text(f"{base}/plug", 60))
    link(corpus / ".config/nvim", "../dotfiles/nvim")
    put(corpus / ".local/bin/corpus-tool", b"#!/bin/sh\necho corpus\n", 0o755)
    put(
        corpus / "Documents/readonly-note.txt", prose(f"{base}/ro", 300).encode(), 0o444
    )
    put(corpus / "Documents/shared.txt", prose(f"{base}/shared", 300).encode(), 0o640)
    for k, name in enumerate(NAMES):
        put(corpus / "names" / name, prose(f"{base}/names/{k}", 64 + k).encode())
    for rel, target in LINKS:
        link(corpus / rel, target)
    deep = corpus / "deep" / "/".join(f"d{k:02d}" for k in range(1, 33))
    put(deep / "leaf.txt", b"leaf\n")
    for rel in EMPTY_DIRS:
        (corpus / rel).mkdir(parents=True, exist_ok=True)


def build_large(corpus: Path, base: str, scale: Scale) -> None:
    for rel, kind, size in scale.large:
        put(corpus / rel, blob(f"{base}/{rel}", kind, size))


def build_cache(corpus: Path, base: str, scale: Scale) -> None:
    det = Det(f"{base}/cache")
    for _ in range(scale.cache_files):
        h = det.hex(16)
        rel = f".cache/agent-cache/{h[0]}/{h[1:3]}/{h}"
        put(corpus / rel, shake(f"{base}/{rel}", 64 + det.below(8 * KIB)))


def build_node(corpus: Path, base: str, scale: Scale) -> None:
    for p in range(scale.node_projects):
        det = Det(f"{base}/node/{p}")
        project = corpus / f"projects/web-{p}"
        put(project / "package.json", json.dumps({"name": f"web-{p}"}).encode())
        for k in range(10):
            put(
                project / f"src/{det.word()}_{k}.ts",
                source_text(f"{base}/web{p}/{k}", 40),
            )
        modules = project / "node_modules"
        for n in range(scale.node_packages):
            scoped = det.chance(8)
            pkg = f"{det.word()}-{det.word()}-{n}"
            pkg = f"@{det.word()}/{pkg}" if scoped else pkg
            label = f"{base}/web{p}/{pkg}"
            meta = {"name": pkg, "version": f"1.{n % 10}.{det.below(20)}"}
            put(modules / pkg / "package.json", json.dumps(meta).encode())
            put(modules / pkg / "index.js", source_text(f"{label}/index", 20))
            put(modules / pkg / "README.md", prose(f"{label}/readme", 400).encode())
            put(modules / pkg / "LICENSE", LICENSE)
            for k in range(det.below(12)):
                put(
                    modules / pkg / f"lib/{det.word()}_{k}.js",
                    source_text(f"{label}/{k}", 30),
                )
            if det.chance(5):
                put(modules / pkg / "bin/cli.js", b"#!/usr/bin/env node\n", 0o755)
                link(modules / ".bin" / f"cli-{n}", f"../{pkg}/bin/cli.js")
            if det.chance(10):
                dep = modules / pkg / "node_modules" / f"{det.word()}-dep"
                put(dep / "package.json", json.dumps({"name": dep.name}).encode())
                put(dep / "index.js", source_text(f"{label}/dep", 10))


def codex_rows(det: Det, label: str, lines: int) -> list[object]:
    start = HISTORY_EPOCH + det.below(270 * 86_400)
    sid = det.uuid()
    meta = {"id": sid, "cwd": f"/home/agent/git/{det.word()}", "originator": "cli"}
    rows: list[object] = [
        {"timestamp": iso(start), "type": "session_meta", "payload": meta}
    ]
    for k in range(1, lines):
        kind = det.choice(
            ("message", "function_call", "function_call_output", "reasoning")
        )
        payload = {"type": kind, "text": prose(f"{label}/{k}", det.between(40, 1_600))}
        if kind == "message":
            payload["role"] = det.choice(("user", "assistant"))
        rows.append(
            {
                "timestamp": iso(start + 7 * k),
                "type": "response_item",
                "payload": payload,
            }
        )
    return rows


def claude_rows(det: Det, label: str, lines: int, cwd: str) -> list[object]:
    start = HISTORY_EPOCH + det.below(270 * 86_400)
    sid = det.uuid()
    parent = None
    rows: list[object] = []
    for k in range(lines):
        uid = det.uuid()
        role = ("user", "assistant")[k % 2]
        rows.append(
            {
                "parentUuid": parent,
                "isSidechain": False,
                "cwd": cwd,
                "sessionId": sid,
                "type": role,
                "message": {
                    "role": role,
                    "content": prose(f"{label}/{k}", det.between(40, 1_600)),
                },
                "uuid": uid,
                "timestamp": iso(start + 11 * k),
            }
        )
        parent = uid
    return rows


def zstd_compress(data: bytes) -> bytes:
    args = ["zstd", "-q", "-c", "-3", "--single-thread", "--no-progress"]
    return subprocess.run(args, input=data, capture_output=True, check=True).stdout


def sqlite_db(path: Path, label: str, rows: int) -> int:
    """A journal_mode=DELETE store with deleted rows (free pages); returns rows."""
    path.parent.mkdir(parents=True, exist_ok=True)
    det = Det(label)
    con = sqlite3.connect(path, isolation_level=None)
    try:
        con.execute("PRAGMA page_size=4096")
        con.execute("PRAGMA journal_mode=DELETE")
        con.execute(
            "CREATE TABLE threads(id TEXT PRIMARY KEY, created INTEGER, title TEXT)"
        )
        con.execute(
            "CREATE TABLE items(id INTEGER PRIMARY KEY, thread TEXT, role TEXT,"
            " body BLOB)"
        )
        con.execute("CREATE INDEX items_thread ON items(thread)")
        threads = [det.uuid() for _ in range(max(1, rows // 50))]
        con.execute("BEGIN")
        con.executemany(
            "INSERT INTO threads VALUES (?, ?, ?)",
            [
                (t, HISTORY_EPOCH + n, prose(f"{label}/t{n}", 48))
                for n, t in enumerate(threads)
            ],
        )
        con.executemany(
            "INSERT INTO items(thread, role, body) VALUES (?, ?, ?)",
            [
                (
                    det.choice(threads),
                    det.choice(("user", "assistant", "tool")),
                    prose(f"{label}/i{k}", det.between(40, 900)).encode(),
                )
                for k in range(rows)
            ],
        )
        con.execute("COMMIT")
        con.execute("DELETE FROM items WHERE id % 7 = 3")
        con.execute("PRAGMA user_version = 7")
        return con.execute("SELECT count(*) FROM items").fetchone()[0]
    finally:
        con.close()


def wal_checksum(data: bytes, big: bool, s0: int, s1: int) -> tuple[int, int]:
    words = struct.unpack(f"{'>' if big else '<'}{len(data) // 4}I", data)
    for i in range(0, len(words), 2):
        s0 = (s0 + words[i] + s1) & 0xFFFFFFFF
        s1 = (s1 + words[i + 1] + s0) & 0xFFFFFFFF
    return s0, s1


def wal_fix_salts(wal: bytes, salt1: int, salt2: int) -> bytes:
    """Rewrite a fresh WAL's random salts and recompute every checksum."""
    magic, _version, page_size, _seq, old1, old2 = struct.unpack(">6I", wal[:24])
    if magic not in (0x377F0682, 0x377F0683) or (len(wal) - 32) % (24 + page_size):
        raise CorpusError("unexpected WAL layout")
    big = bool(magic & 1)
    header = bytearray(wal[:32])
    struct.pack_into(">II", header, 16, salt1, salt2)
    s0, s1 = wal_checksum(bytes(header[:24]), big, 0, 0)
    struct.pack_into(">II", header, 24, s0, s1)
    out = bytearray(header)
    for pos in range(32, len(wal), 24 + page_size):
        frame = bytearray(wal[pos : pos + 24])
        page = wal[pos + 24 : pos + 24 + page_size]
        if struct.unpack_from(">II", frame, 8) != (old1, old2):
            raise CorpusError("WAL frame from an older generation")
        struct.pack_into(">II", frame, 8, salt1, salt2)
        s0, s1 = wal_checksum(bytes(frame[:8]), big, s0, s1)
        s0, s1 = wal_checksum(page, big, s0, s1)
        struct.pack_into(">II", frame, 16, s0, s1)
        out += frame + page
    return bytes(out)


def sqlite_wal_image(target: Path, label: str, rows: int, scratch: Path) -> None:
    work = scratch / "wal-image"
    work.mkdir()
    db = work / "storage.db"
    sqlite_db(db, label, rows)
    det = Det(f"{label}/wal")
    con = sqlite3.connect(db, isolation_level=None)
    try:
        if con.execute("PRAGMA journal_mode=WAL").fetchone()[0] != "wal":
            raise CorpusError("SQLite refused WAL mode")
        con.execute("PRAGMA wal_autocheckpoint=0")
        for t in range(3):
            con.execute("BEGIN")
            con.executemany(
                "INSERT INTO items(thread, role, body) VALUES (?, ?, ?)",
                [
                    (
                        "wal",
                        "tool",
                        prose(f"{label}/w{t}/{k}", det.between(40, 900)).encode(),
                    )
                    for k in range(40)
                ],
            )
            con.execute("COMMIT")
        expected = con.execute("SELECT count(*) FROM items").fetchone()[0]
        main = db.read_bytes()
        wal = (work / "storage.db-wal").read_bytes()
    finally:
        con.close()
    salt1, salt2 = struct.unpack(">II", shake(f"{label}/salts", 8))
    fixed = wal_fix_salts(wal, salt1, salt2)
    probe = scratch / "wal-probe"
    probe.mkdir()
    (probe / "x.db").write_bytes(main)
    (probe / "x.db-wal").write_bytes(fixed)
    con = sqlite3.connect(probe / "x.db")
    try:
        check = con.execute("PRAGMA integrity_check").fetchone()[0]
        count = con.execute("SELECT count(*) FROM items").fetchone()[0]
    finally:
        con.close()
    if check != "ok" or count != expected:
        raise CorpusError(f"WAL image does not recover: {check} {count}/{expected}")
    put(target, main)
    put(target.with_name(target.name + "-wal"), fixed)


def build_agents(
    corpus: Path, base: str, scale: Scale, scratch: Path, notes: list[str]
) -> None:
    det = Det(f"{base}/agents")
    low, high = scale.transcript_lines
    history = []
    for s in range(scale.codex_sessions):
        rows = codex_rows(det, f"{base}/codex/{s}", det.between(low, high))
        stamp = time.strftime(
            "%Y/%m/%d/rollout-%Y-%m-%dT%H-%M-%S",
            time.gmtime(HISTORY_EPOCH + s * 47_123),
        )
        put(corpus / f".codex/sessions/{stamp}-{det.uuid()}.jsonl", jsonl(rows))
        history.append(
            {
                "session_id": det.uuid(),
                "ts": HISTORY_EPOCH + s,
                "text": prose(f"{base}/h{s}", 80),
            }
        )
    put(corpus / ".codex/history.jsonl", jsonl(history))
    put(corpus / ".codex/config.toml", b'model = "corpus"\napproval_policy = "never"\n')
    put(
        corpus / ".codex/log/codex-tui.log",
        prose(f"{base}/tui", 4_000 + 40 * scale.codex_sessions).encode(),
    )
    if shutil.which("zstd"):
        for z in range(scale.zst_sessions):
            rows = codex_rows(det, f"{base}/zst/{z}", det.between(low, high))
            put(
                corpus / f".codex/sessions/archive/rollout-{det.uuid()}.jsonl.zst",
                zstd_compress(jsonl(rows)),
            )
    else:
        notes.append("zstd not on PATH: .jsonl.zst archives skipped")
    projects: dict[str, int] = {}
    for s in range(scale.claude_sessions):
        repo = repo_name(s % scale.repos)
        cwd = f"/home/agent/git/{repo}"
        rows = claude_rows(det, f"{base}/claude/{s}", det.between(low, high), cwd)
        put(
            corpus / f".claude/projects/-home-agent-git-{repo}/{det.uuid()}.jsonl",
            jsonl(rows),
        )
        projects[cwd] = projects.get(cwd, 0) + 1
        if s % 4 == 0:
            todos = [
                {"content": prose(f"{base}/todo/{s}/{k}", 60), "status": "pending"}
                for k in range(3)
            ]
            put(
                corpus / f".claude/todos/{det.uuid()}-agent-{det.uuid()}.json",
                json.dumps(todos).encode(),
            )
    put(corpus / ".claude/settings.json", json.dumps({"model": "corpus"}).encode())
    state = {"projects": {k: {"sessions": v} for k, v in sorted(projects.items())}}
    put(corpus / ".claude.json", json.dumps(state, indent=2).encode())
    put(
        corpus / ".claude/shell-snapshots/snapshot-bash-1.sh",
        source_text(f"{base}/snap", 50),
    )
    dbs = [
        ".codex/state.sqlite",
        ".config/Code/User/globalStorage/state.vscdb",
        ".local/share/agent-kv/kv.sqlite",
    ]
    dbs += [
        f".local/share/agent-cache/cache-{k}.sqlite"
        for k in range(scale.sqlite_dbs - 3)
    ]
    for k, rel in enumerate(dbs[: scale.sqlite_dbs]):
        sqlite_db(corpus / rel, f"{base}/sqlite/{k}", det.between(*scale.sqlite_rows))
        (corpus / rel).chmod(0o644)
    low_rows = scale.sqlite_rows[0]
    sqlite_wal_image(
        corpus / ".local/share/opencode/storage.db", f"{base}/wal", low_rows, scratch
    )


# ---- manifest and identity -------------------------------------------------------


def esc(text: str) -> str:
    out = []
    for ch in text:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif 0xDC80 <= o <= 0xDCFF:
            out.append(f"\\x{o & 0xFF:02x}")
        elif o < 0x20 or o == 0x7F:
            out.append(f"\\x{o:02x}")
        else:
            out.append(ch)
    return "".join(out)


def walk(corpus: Path) -> list[tuple[str, os.stat_result]]:
    out = []
    stack = [""]
    while stack:
        rel = stack.pop()
        with os.scandir(corpus / rel if rel else corpus) as entries:
            for entry in entries:
                child = f"{rel}/{entry.name}" if rel else entry.name
                info = entry.stat(follow_symlinks=False)
                out.append((child, info))
                if stat.S_ISDIR(info.st_mode):
                    stack.append(child)
    out.sort(key=lambda row: os.fsencode(row[0]))
    return out


def index_logical(data: bytes) -> bytes:
    """A git index without its stat words and trailing checksum."""
    if data[:4] != b"DIRC":
        raise CorpusError("not a DIRC index")
    version, count = struct.unpack(">II", data[4:12])
    if version not in (2, 3):
        raise CorpusError(f"index version {version}")
    out = bytearray(data[:12])
    pos = 12
    for _ in range(count):
        mode = struct.unpack_from(">I", data, pos + 24)[0]
        out += struct.pack(">10I", 0, 0, 0, 0, 0, 0, mode, 0, 0, 0)
        flags = struct.unpack_from(">H", data, pos + 60)[0]
        name = pos + (64 if flags & 0x4000 else 62)
        # On disk an entry is padded with 1-8 NULs to a multiple of 8 bytes.
        size = (data.index(b"\0", name) - pos + 8) & ~7
        out += data[pos + 40 : pos + size]
        pos += size
    extensions = pos
    tail = len(data) - 20
    while pos < tail:
        sig = data[pos : pos + 4]
        if sig in (b"UNTR", b"FSMN", b"link"):
            raise CorpusError(f"stat-bearing index extension {sig.decode()}")
        pos += 8 + struct.unpack_from(">I", data, pos + 4)[0]
    if pos != tail:
        raise CorpusError("index extensions overrun")
    return bytes(out + data[extensions:tail])


def is_gitdir_name(name: str) -> bool:
    return name == ".git" or name.endswith(".git")


def norm_kind(parts: list[str]) -> str:
    """Which normalisation a regular file gets (see the module docstring)."""
    if parts[-1] == ".git":
        return "root"
    admin = len(parts) >= 4 and parts[-3] == "worktrees" and is_gitdir_name(parts[-4])
    if parts[-1] == "gitdir" and admin:
        return "root"
    if parts[-1] == "index" and (
        admin or (len(parts) >= 2 and is_gitdir_name(parts[-2]))
    ):
        return "git-index"
    return "raw"


def digest_file(path: Path) -> tuple[int, str, bytes]:
    h = hashlib.shake_256()
    size = 0
    head = b""
    with path.open("rb") as handle:
        while chunk := handle.read(BLOCK):
            if not head:
                head = chunk[:16]
            h.update(chunk)
            size += len(chunk)
    return size, h.hexdigest(32), head


def manifest(corpus: Path, root: str) -> tuple[str, list[str], dict[str, int]]:
    """The canonical manifest of `corpus`, its problems and its counts."""
    root_bytes = os.fsencode(root)
    problems: list[str] = []
    counts = dict.fromkeys(
        (
            "entries",
            "dirs",
            "files",
            "symlinks",
            "bytes",
            "empty_dirs",
            "git_dirs",
            "bare_repos",
            "worktree_admins",
            "gitfiles",
            "git_indexes",
            "loose_objects",
            "packs",
            "jsonl",
            "jsonl_zst",
            "sqlite",
            "sqlite_wal",
            "large_files",
            "small_files",
        ),
        0,
    )
    entries = walk(corpus)
    children: dict[str, int] = {}
    for rel, _info in entries:
        parent = rel.rpartition("/")[0]
        children[parent] = children.get(parent, 0) + 1
    lines = [MANIFEST_HEADER]
    for rel, info in entries:
        parts = rel.split("/")
        in_git = any(is_gitdir_name(p) for p in parts[:-1])
        mode = info.st_mode
        counts["entries"] += 1
        if stat.S_ISDIR(mode):
            counts["dirs"] += 1
            counts["empty_dirs"] += children.get(rel, 0) == 0
            counts["git_dirs"] += parts[-1] == ".git"
            counts["bare_repos"] += parts[-1].endswith(".git") and parts[-1] != ".git"
            counts["worktree_admins"] += (
                len(parts) >= 3
                and parts[-2] == "worktrees"
                and parts[-3].endswith(".git")
            )
            row = (rel, "d", f"{mode & 0o7777:04o}", "-", "-", "-", "-")
        elif stat.S_ISLNK(mode):
            counts["symlinks"] += 1
            target = os.readlink(corpus / rel)
            size = str(len(os.fsencode(target)))
            row = (rel, "l", "-", size, "-", esc(target), "-")
        elif stat.S_ISREG(mode):
            counts["files"] += 1
            norm = norm_kind(parts)
            path = corpus / rel
            if norm == "raw" and not (in_git and info.st_size <= LEAK_SCAN_LIMIT):
                size, digest, head = digest_file(path)
            else:
                data = path.read_bytes()
                head = data[:16]
                size = len(data)
                if norm == "raw" and root_bytes in data:
                    problems.append(f"absolute corpus root inside {rel}")
                elif norm == "root":
                    data = data.replace(root_bytes, ROOT_TOKEN)
                    size = len(data)
                    counts["gitfiles"] += parts[-1] == ".git"
                elif norm == "git-index":
                    counts["git_indexes"] += 1
                    try:
                        data = index_logical(data)
                    except (CorpusError, ValueError, struct.error) as err:
                        problems.append(f"index {rel}: {err}")
                digest = hashlib.shake_256(data).hexdigest(32)
            name = parts[-1]
            counts["bytes"] += size
            counts["loose_objects"] += (
                in_git
                and len(parts) >= 3
                and parts[-3] == "objects"
                and len(parts[-2]) == 2
                and len(name) == 38
            )
            counts["packs"] += in_git and name.endswith(".pack")
            counts["jsonl"] += name.endswith(".jsonl")
            counts["jsonl_zst"] += name.endswith(".jsonl.zst")
            counts["sqlite"] += head == b"SQLite format 3\0"
            counts["sqlite_wal"] += name.endswith("-wal")
            counts["large_files"] += info.st_size >= MIB
            counts["small_files"] += info.st_size <= 4 * KIB
            row = (rel, "f", f"{mode & 0o7777:04o}", str(size), digest, "-", norm)
        else:
            problems.append(f"not a file, directory or symlink: {rel}")
            continue
        lines.append("\t".join((esc(row[0]), *row[1:])) + "\n")
    return "".join(lines), problems, counts


def identity_of(text: str) -> str:
    return hashlib.shake_256(text.encode()).hexdigest(32)


def rows_of(text: str) -> dict[str, list[str]]:
    rows = {}
    for line in text.splitlines()[1:]:
        fields = line.split("\t")
        rows[fields[0]] = fields
    return rows


def diff_rows(
    before: dict[str, list[str]], after: dict[str, list[str]]
) -> tuple[list[str], list[str], list[str]]:
    def order(paths: Iterable[str]) -> list[str]:
        return sorted(paths, key=str.encode)

    added = order(after.keys() - before.keys())
    removed = order(before.keys() - after.keys())
    modified = order(p for p in before.keys() & after.keys() if before[p] != after[p])
    return added, removed, modified


# ---- seal ------------------------------------------------------------------------------


def toolchain() -> dict[str, str | None]:
    def out(args: list[str]) -> str:
        try:
            return subprocess.run(args, capture_output=True, text=True).stdout
        except OSError:
            return ""

    git = out(["git", "--version"]).split()
    zlib = [
        line.strip()
        for line in out(["git", "version", "--build-options"]).splitlines()
        if line.strip().startswith("zlib")
    ]
    zstd = (
        re.search(r"v(\d+\.\d+\.\d+)", out(["zstd", "-V"]))
        if shutil.which("zstd")
        else None
    )
    return {
        "git": git[-1] if git else None,
        "git_zlib": zlib[0] if zlib else None,
        "sqlite": sqlite3.sqlite_version,
        "zstd": zstd.group(1) if zstd else None,
        "python": platform.python_version(),
    }


def git_version(text: str | None) -> tuple[int, int]:
    match = re.match(r"(\d+)\.(\d+)", text or "")
    return (int(match.group(1)), int(match.group(2))) if match else (0, 0)


def recorded_identity(scale: str, seed: str, tools: dict) -> str | None:
    """The recorded identity for (scale, seed), if this toolchain recorded it."""
    entry = RECORDED.get((scale, seed))
    if entry and all(tools.get(key) == value for key, value in entry[1].items()):
        return entry[0]
    return None


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def readme(seal: dict) -> str:
    return (
        f"# Estate-shaped corpus v1 ({seal['identity'][:16]})\n\n"
        "Generated by bulkload `crates/bulkload-bench/scripts/estate_corpus.py`\n"
        f"(WP0(e), OI-1003-Q19) with seed `{seal['seed']}` and scale "
        f"`{seal['scale']}`.\n\n"
        f"- Identity (SHAKE-256/256 of MANIFEST.tsv): `{seal['identity']}`\n"
        f"- {seal['counts']['entries']:,} entries, {seal['counts']['files']:,} files, "
        f"{seal['counts']['bytes']:,} bytes under `corpus/`.\n"
        "- Check before use: `estate_corpus.py verify <this dir>`.\n"
        "- Not relocatable: linked worktrees point at the absolute generation path,\n"
        "  so never run git in a moved copy.\n"
    )


def generate(dest: Path, seed: str, scale_name: str) -> tuple[int, str | None]:
    if dest.exists() or not dest.parent.is_dir():
        print(
            f"estate-corpus refused: DEST must be new under an existing parent: {dest}"
        )
        return 2, None
    tools = toolchain()
    if git_version(tools["git"]) < MIN_GIT:
        print(f"estate-corpus refused: git >= 2.45 required, found {tools['git']}")
        return 2, None
    os.umask(0o022)
    started = time.monotonic()
    scale = SCALES[scale_name]
    base = f"{seed}/{scale_name}"
    dest.mkdir()
    corpus = dest / "corpus"
    corpus.mkdir()
    root = os.path.realpath(corpus)
    notes: list[str] = []
    repos = []
    with tempfile.TemporaryDirectory(prefix="estate-corpus-git-") as raw:
        scratch = Path(raw)
        build_home(Path(root), base)
        build_large(Path(root), base, scale)
        build_cache(Path(root), base, scale)
        build_node(Path(root), base, scale)
        build_agents(Path(root), base, scale, scratch, notes)
        g = Git(scratch, Path(root), HISTORY_EPOCH)
        for i in range(scale.repos):
            repos.append(build_repo(g, Path(root), base, scale, i))
    text, problems, counts = manifest(Path(root), root)
    identity = identity_of(text)
    recorded = recorded_identity(scale_name, seed, tools)
    if recorded and recorded != identity:
        problems.append(f"identity differs from the recorded {recorded}")
    seal = {
        "format": FORMAT,
        "seed": seed,
        "scale": scale_name,
        "identity": identity,
        "base_identity": identity,
        "identity_algorithm": "SHAKE-256/256 of MANIFEST.tsv",
        "root": root,
        "counts": counts,
        "repos": repos,
        "tools": tools,
        "notes": notes,
        "generator": "crates/bulkload-bench/scripts/estate_corpus.py",
        "generator_shake256": hashlib.shake_256(HERE.read_bytes()).hexdigest(32),
        "mutations": [],
    }
    (dest / "MANIFEST.tsv").write_text(text)
    write_json(dest / "SEAL.json", seal)
    (dest / "README.md").write_text(readme(seal))
    for problem in problems:
        print(f"estate-corpus problem: {problem}")
    print(
        f"estate-corpus generated={corpus} scale={scale_name} seed={seed} "
        f"entries={counts['entries']} files={counts['files']} dirs={counts['dirs']} "
        f"symlinks={counts['symlinks']} bytes={counts['bytes']} "
        f"seconds={time.monotonic() - started:.1f} identity={identity} "
        f"recorded={'none' if recorded is None else recorded == identity}"
    )
    return (1 if problems else 0), identity


def load_seal(dest: Path) -> dict | None:
    try:
        return json.loads((dest / "SEAL.json").read_text())
    except (OSError, ValueError):
        return None


def verify(dest: Path) -> int:
    seal = load_seal(dest)
    corpus = dest / "corpus"
    if seal is None or not corpus.is_dir():
        print(f"estate-corpus verify dest={dest} missing=1 ok=False")
        return 1
    text, problems, _counts = manifest(corpus, seal["root"])
    identity = identity_of(text)
    for problem in problems:
        print(f"estate-corpus problem: {problem}")
    ok = not problems and identity == seal["identity"]
    if not ok and (dest / "MANIFEST.tsv").is_file():
        sealed = rows_of((dest / "MANIFEST.tsv").read_text())
        added, removed, modified = diff_rows(sealed, rows_of(text))
        for sign, paths in (("+", added), ("-", removed), ("~", modified)):
            for path in paths[:20]:
                print(f"estate-corpus differs: {sign} {path}")
    relocated = os.path.realpath(corpus) != seal["root"]
    print(
        f"estate-corpus verify dest={dest} identity={identity} "
        f"expected={seal['identity']} relocated={int(relocated)} ok={ok}"
    )
    return 0 if ok else 1


# ---- mutation (the S3 knob) ---------------------------------------------------------


def stat_key(info: os.stat_result) -> tuple[int, int, int, int, int]:
    return (info.st_ino, info.st_size, info.st_mtime_ns, info.st_ctime_ns, info.st_mode)


def mutate(dest: Path, count: int) -> int:
    seal = load_seal(dest)
    corpus = dest / "corpus"
    if seal is None or count < 1:
        print(f"estate-corpus refused: mutate needs a sealed DEST and N >= 1: {dest}")
        return 2
    root = seal["root"]
    if os.path.realpath(corpus) != root:
        print(f"estate-corpus refused: mutate runs in place only (sealed at {root})")
        return 2
    before_text, problems, _ = manifest(corpus, root)
    if problems or identity_of(before_text) != seal["identity"]:
        print("estate-corpus refused: the corpus does not match its seal")
        return 2
    before = rows_of(before_text)
    # Manifest rows are keyed by escaped path; `raw` maps back to file names.
    entries = walk(corpus)
    raw = {esc(rel): rel for rel, _info in entries}
    stats_before = {esc(rel): stat_key(info) for rel, info in entries}
    rnd = len(seal["mutations"]) + 1
    label = f"{seal['seed']}/{seal['scale']}/mutation/{rnd}"
    det = Det(label)
    detached = [
        w for r in seal["repos"] for w in r["worktrees"] if w["kind"] == "detached"
    ]
    fenced = tuple(w["path"] + "/" for w in detached)

    def editable(rel: str, row: list[str]) -> bool:
        parts = rel.split("/")
        return (
            not any(is_gitdir_name(p) for p in parts)
            and not (rel + "/").startswith(fenced)
            and int(row[2], 8) & 0o200 != 0
        )

    files = [p for p, r in before.items() if r[1] == "f" and editable(p, r)]
    db_like = (".sqlite", ".db", ".vscdb", "-wal", ".zst")
    plain = sorted((p for p in files if not p.endswith(db_like)), key=str.encode)
    pools = {
        "edit": [p for p in plain if not p.endswith(".jsonl") and before[p][3] != "0"],
        "append": [p for p in plain if p.endswith(".jsonl")],
        "delete": [p for p in plain if int(before[p][3]) <= MIB],
        "new": sorted(
            (p for p, r in before.items() if r[1] == "d" and editable(p, r)),
            key=str.encode,
        ),
    }
    repos = sorted(r["path"] for r in seal["repos"])
    for kind, targets in (*pools.items(), ("commit", repos), ("head-move", detached)):
        if not targets:
            print(f"estate-corpus refused: no target for a {kind} mutation")
            return 2
    order = det.shuffled(KINDS)
    used: set[str] = set()
    operations = []
    with tempfile.TemporaryDirectory(prefix="estate-corpus-git-") as tmp:
        g = Git(Path(tmp), Path(root), MUTATION_EPOCH + rnd * 86_400)
        for k in range(count):
            kind = order[k % len(order)]
            op = {"op": k, "kind": kind}
            if kind in ("edit", "append", "delete"):
                pool = [p for p in pools[kind] if p not in used]
                rel = det.choice(pool)
                used.add(rel)
                path = corpus / raw[rel]
                if kind == "edit":
                    size = path.stat().st_size
                    width = min(64, size)
                    at = (size // 2) & ~63 if size >= 128 else 0
                    fresh = prose(f"{label}/{k}", width).encode()
                    with path.open("r+b") as handle:
                        handle.seek(at)
                        old = handle.read(width)
                        if fresh == old:
                            fresh = bytes([fresh[0] ^ 1]) + fresh[1:]
                        handle.seek(at)
                        handle.write(fresh)
                    op.update(path=rel, offset=at, length=width)
                elif kind == "append":
                    row = {
                        "type": "mutation",
                        "round": rnd,
                        "text": prose(f"{label}/{k}", 200),
                    }
                    with path.open("ab") as handle:
                        handle.write(jsonl([row]))
                    op.update(path=rel)
                else:
                    path.unlink()
                    op.update(path=rel)
            elif kind == "new":
                parent = det.choice(pools["new"])
                name = f"mutation-r{rnd:04d}-{k:02d}.md"
                rel = f"{parent}/{name}"
                put(
                    corpus / raw[parent] / name,
                    prose(f"{label}/{k}", det.between(512, 8 * KIB)).encode(),
                )
                used.add(rel)
                op.update(path=rel)
            elif kind == "commit":
                repo_rel = det.choice(repos)
                repo = corpus / repo_rel
                old = g.run(repo, "rev-parse", "--verify", "refs/heads/side").strip()
                listing = g.run(
                    repo, "ls-tree", "-r", "--format=%(objectmode) %(path)", old
                )
                blobs = sorted(
                    (
                        line.split(" ", 1)[1]
                        for line in listing.splitlines()
                        if line.startswith("100644 ")
                    ),
                    key=str.encode,
                )
                target = det.choice(blobs)
                content = g.raw(repo, "cat-file", "blob", f"{old}:{target}")
                fresh = content + source_text(f"{label}/{k}", 3)
                oid = g.run(repo, "hash-object", "-w", "--stdin", stdin=fresh).strip()
                index = {"GIT_INDEX_FILE": str(Path(tmp) / f"index-{k}")}
                g.run(repo, "read-tree", old, extra=index)
                g.run(
                    repo,
                    "update-index",
                    "--cacheinfo",
                    f"100644,{oid},{target}",
                    extra=index,
                )
                tree = g.run(repo, "write-tree", extra=index).strip()
                message = f"side: mutation round {rnd} op {k}"
                new = g.run(repo, "commit-tree", tree, "-p", old, "-m", message).strip()
                g.run(
                    repo,
                    "update-ref",
                    "-m",
                    f"commit: {message}",
                    "refs/heads/side",
                    new,
                    old,
                )
                op.update(
                    path=f"{repo_rel}/.git/refs/heads/side",
                    repo=repo_rel,
                    file=target,
                    old=old,
                    new=new,
                )
            else:
                wt = detached[det.below(len(detached))]
                wpath = corpus / wt["path"]
                head = g.run(wpath, "rev-parse", "HEAD").strip()
                history = g.run(wpath, "rev-list", "--first-parent", "main").split()
                target = det.choice([c for c in history if c != head])
                g.run(wpath, "checkout", "-q", "--detach", target)
                op.update(
                    path=f"{wt['admin']}/HEAD",
                    worktree=wt["path"],
                    old=head,
                    new=target,
                )
            operations.append(op)
    after_text, problems, counts = manifest(corpus, root)
    for problem in problems:
        print(f"estate-corpus problem: {problem}")
    after = rows_of(after_text)
    stats_after = {esc(rel): stat_key(info) for rel, info in walk(corpus)}
    added, removed, modified = diff_rows(before, after)
    stat_only = sorted(
        (
            p
            for p in stats_before.keys() & stats_after.keys()
            if before[p] == after[p] and stats_before[p] != stats_after[p]
        ),
        key=str.encode,
    )
    reads = sorted(
        (p for p in {*added, *modified, *stat_only} if after[p][1] == "f"),
        key=str.encode,
    )
    identity = identity_of(after_text)
    sidecar = {
        "format": FORMAT,
        "round": rnd,
        "count": count,
        "seed": seal["seed"],
        "scale": seal["scale"],
        "identity_before": seal["identity"],
        "identity_after": identity,
        "operations": operations,
        "changed": {"added": added, "removed": removed, "modified": modified},
        "stat_only": stat_only,
        "reads_allowed": reads,
    }
    out = dest / "mutations" / f"round-{rnd:04d}.json"
    out.parent.mkdir(exist_ok=True)
    write_json(out, sidecar)
    seal["mutations"].append(
        {
            "round": rnd,
            "count": count,
            "sidecar": str(out.relative_to(dest)),
            "identity_before": seal["identity"],
            "identity_after": identity,
        }
    )
    seal["identity"] = identity
    seal["counts"] = counts
    (dest / "MANIFEST.tsv").write_text(after_text)
    write_json(dest / "SEAL.json", seal)
    print(
        f"estate-corpus mutated={corpus} round={rnd} operations={count} "
        f"added={len(added)} removed={len(removed)} modified={len(modified)} "
        f"stat_only={len(stat_only)} reads_allowed={len(reads)} identity={identity}"
    )
    return 1 if problems else 0


# ---- self-test ---------------------------------------------------------------------------


def selftest() -> int:
    """Generate scale=small twice, verify, mutate and tamper (optional tier)."""
    started = time.monotonic()
    temps = [
        Path(tempfile.mkdtemp(prefix=f"estate-corpus-selftest-{n}-")) for n in "ab"
    ]
    failures: list[str] = []

    def check(ok: bool, what: str) -> None:
        print(f"estate-corpus selftest {'ok' if ok else 'FAIL'}: {what}")
        if not ok:
            failures.append(what)

    try:
        a, b = (t / "dest" for t in temps)
        rc_a, id_a = generate(a, DEFAULT_SEED, "small")
        rc_b, id_b = generate(b, DEFAULT_SEED, "small")
        check(rc_a == 0 and rc_b == 0, "both generations are clean")
        check(id_a == id_b, f"two generations share one identity ({id_a})")
        check(
            (a / "MANIFEST.tsv").read_bytes() == (b / "MANIFEST.tsv").read_bytes(),
            "the two manifests are byte-identical",
        )
        tools = load_seal(a)["tools"]
        recorded = recorded_identity("small", DEFAULT_SEED, tools)
        if recorded:
            check(id_a == recorded, f"identity equals the recorded {recorded[:16]}")
        else:
            print(f"estate-corpus selftest note: nothing recorded for tools {tools}")
        check(verify(a) == 0, "verify accepts the sealed corpus")
        before = rows_of((a / "MANIFEST.tsv").read_text())
        check(mutate(a, len(KINDS)) == 0, "mutate applies one of each operation")
        check(mutate(b, len(KINDS)) == 0, "mutate applies to the second copy")
        side = json.loads((a / "mutations/round-0001.json").read_text())
        twin = json.loads((b / "mutations/round-0001.json").read_text())
        after = rows_of((a / "MANIFEST.tsv").read_text())
        added, removed, modified = diff_rows(before, after)
        check(
            side["identity_after"] != side["identity_before"],
            "mutation changes the identity",
        )
        check(
            side["identity_after"] == twin["identity_after"],
            "mutation is deterministic",
        )
        check(
            side["changed"]
            == {"added": added, "removed": removed, "modified": modified},
            "the sidecar lists exactly the manifest difference",
        )
        check(
            {op["kind"] for op in side["operations"]} == set(KINDS), "all six kinds ran"
        )
        changed = {*added, *removed, *modified}
        check(
            all(op["path"] in changed for op in side["operations"]),
            "every operation's path is in the difference",
        )
        content = {p for p in (*added, *modified) if after[p][1] == "f"}
        check(
            content <= set(side["reads_allowed"]),
            "reads_allowed covers every changed file",
        )
        check(verify(a) == 0, "verify accepts the mutated corpus against its new seal")
        victim = b / "corpus" / "names" / "with space.txt"
        with victim.open("ab") as handle:
            handle.write(b"!")
        check(verify(b) == 1, "verify rejects a tampered byte")
    except (
        CorpusError,
        OSError,
        KeyError,
        ValueError,
        subprocess.SubprocessError,
    ) as err:
        check(False, f"self-test raised {type(err).__name__}: {err}")
    finally:
        for temp in temps:
            shutil.rmtree(temp, ignore_errors=True)
        check(not any(t.exists() for t in temps), "temporary corpora removed")
    print(
        f"estate-corpus selftest failures={len(failures)} "
        f"seconds={time.monotonic() - started:.1f} ok={not failures}"
    )
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("generate", help="build a new corpus under DEST")
    gen.add_argument("dest")
    gen.add_argument("--seed", default=DEFAULT_SEED)
    gen.add_argument("--scale", choices=sorted(SCALES), default="small")
    ver = sub.add_parser("verify", help="check DEST/corpus against DEST/SEAL.json")
    ver.add_argument("dest")
    man = sub.add_parser("manifest", help="print the canonical manifest")
    man.add_argument("corpus")
    man.add_argument("--root", help="corpus root to normalise (default: CORPUS)")
    mut = sub.add_parser("mutate", help="the S3 knob: apply N changes in place")
    mut.add_argument("dest")
    mut.add_argument("count", metavar="N", type=int)
    sub.add_parser("selftest", help="optional-tier round trip at scale small")
    args = parser.parse_args(argv)
    try:
        if args.command == "generate":
            return generate(Path(args.dest).absolute(), args.seed, args.scale)[0]
        if args.command == "verify":
            return verify(Path(args.dest).absolute())
        if args.command == "mutate":
            return mutate(Path(args.dest).absolute(), args.count)
        if args.command == "selftest":
            return selftest()
        corpus = Path(args.corpus).absolute()
        text, problems, _ = manifest(corpus, args.root or os.path.realpath(corpus))
        sys.stdout.write(text)
        print(f"identity={identity_of(text)} problems={problems}", file=sys.stderr)
        return 1 if problems else 0
    except CorpusError as err:
        print(f"estate-corpus failed: {err}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
